---
- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Add nginx configuration template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/
    owner: www-data
    group: www-data
    mode: '0664'
    notify:
      - restart-nginx

- name: Ensure nginx is running
  systemd:
    name: nginx
    state: started
    enabled: yes

